### ISSUE TITLE
Overlay image does not fluently move around

### ISSUE THREAD

**Issue by sviplab** [firebug/pixel-perfect#54]
overlay image displayed on browser window does not moves fluently when image is drag around. Its like flickering of image at end of drag. It kind a moves back and forth for while. Previously in earlier version of pixel perfect image moves easily in all direction.

**Comment by janodvarko** [comment]
What OS are you using?

Honza

**Comment by sviplab** [comment]
Win 7

**Comment by janodvarko** [comment]
How big is the image? (size on disk + dimensions). Could the size be the problem?

Could you attach it somewhere, so we can test it?

Honza

**Comment by SebastianZ** [comment]
I also realized that yesterday on Win8.1 with beta 2. Beta 1 was working fine. I didn't have time yet to further investigate what change caused this, though. On my Win7 PC it's working fine.

The size of the image doesn't seem to play a role.

Sebastian

**Comment by janodvarko** [comment]
I can't reproduce this on my machines (Win 7 and OS X).

@sviplab Does beta 1 work for you?

Honza

**Comment by sviplab** [comment]
@janodvarko no, it had also same problem

**Comment by janodvarko** [comment]
@sviplab What exactly do you seeing? Could you create a screencast?
Could it be related to the size of the image?

Honza

**Comment by sviplab** [comment]
@janodvarko yeah in bigger image i felt the problem, it is hard to say but sometimes it is working sometimes it is glitching. last night i checked on my laptop i faced the problem, but i haven't felt much problem in widescreen desktop.

**Comment by janodvarko** [comment]
Could you create a screencast from your laptop?
Honza

**Comment by sviplab** [comment]
i have tested from my laptop there is problem when i drag the overlay image.
I have uploaded the video in YouTube.
Here is the link https://www.youtube.com/watch?v=OxQSCOVKevM&feature=youtu.be
i have tried both with big and small image, but problem remains same on both. if you also notice, X & Y coordinate value, it is jumping from one point to another which should be smooth increment or decrement.

**Comment by janodvarko** [comment]
Thanks for the screencast, that was great help!

I committed a patch that should solve the problem (see the link above)

Could you please test it?
Do you want me to create XPI from the source?

Create XPI:

```
git clone https://github.com/firebug/pixel-perfect.git
cd pixel-perfect
jpm xpi
```

Honza

**Comment by janodvarko** [comment]
Updated instructions:

```
git clone https://github.com/firebug/pixel-perfect.git
cd pixel-perfect
npm install
jpm xpi
```

Honza

**Comment by janodvarko** [comment]
Test XPI available at:
http://janodvarko.cz/temp/pixel-perfect/pixelperfect-2.0.0-beta.2.issue54.xpi

Honza

**Comment by sviplab** [comment]
so sorry for the late response, i was having internet connection problem
it is much easier to drag image now, but still little problem remaining.
here is screen-cast https://www.youtube.com/watch?v=e3Md6hJRYAk

**Comment by janodvarko** [comment]
> so sorry for the late response, i was having internet connection problem

Not a problem

> it is much easier to drag image now, but still little problem remaining.
> here is screen-cast https://www.youtube.com/watch?v=e3Md6hJRYAk

I've seen the screen cast, but what is the little problem?

Honza

**Comment by sviplab** [comment]
i mean to say that it is still not fully fluent in movement. Anyway it is far better than before if this is best we can fix then its ok.

**Comment by janodvarko** [comment]
The only thing I could do is disabling live update of coordinates in the popup panel. This update requires communication over RDP (remote debugging protocol) and can cause a little delays during dragging (there could be perhaps hidden option). But, let's wait if the current optimization is a big problem for other users....

I am closing this one for now.

Thanks for the help!

Honza

**Comment by SebastianZ** [comment]
> I committed a patch that should solve the problem (see the link above)

FWIW it fixed the problem for me.

Sebastian

**Comment by janodvarko** [comment]
One more commit that could have positive impact on this:
https://github.com/firebug/pixel-perfect/commit/323bd12629a34822e3a95120788ab9ca28ee2405
(but's it's a little detail, so not sure)

In any case it'll be in Pixel Perfect 2.0.2+

Honza
